import { getThemeBootstrapScript } from "../shared/theme-bootstrap.js";

export function getIndexHtmlTemplate(projectName: string): string {
  const description = `Starter app generated by Forge for ${projectName}.`;

  return `<!doctype html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="/favicon.ico" sizes="any" type="image/x-icon" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="manifest" href="/site.webmanifest" />
    <meta name="description" content="${description}" />
    <meta name="robots" content="index, follow" />
    <meta property="og:title" content="${projectName}" />
    <meta property="og:description" content="${description}" />
    <meta property="og:type" content="website" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${projectName}" />
    <meta name="twitter:description" content="${description}" />
    <meta name="color-scheme" content="dark light" />
    <script>${getThemeBootstrapScript()}</script>
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

export function getMainTemplate(rtl: boolean): string {
  if (!rtl) {
    return `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router";

import "./index.css";
import App from "./App";
import { AppErrorBoundary } from "@/components/app-error-boundary";
import { AppProviders } from "@/components/app-providers";

const rootElement = document.getElementById("root");

if (!rootElement) {
  throw new Error('Expected the Vite root element with id="root".');
}

createRoot(rootElement).render(
  <StrictMode>
    <AppProviders>
      <BrowserRouter>
        <AppErrorBoundary>
          <App />
        </AppErrorBoundary>
      </BrowserRouter>
    </AppProviders>
  </StrictMode>,
);
`;
  }

  return `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router";

import "./index.css";
import App from "./App";
import { AppErrorBoundary } from "@/components/app-error-boundary";
import { AppProviders } from "@/components/app-providers";

const rootElement = document.getElementById("root");

if (!rootElement) {
  throw new Error('Expected the Vite root element with id="root".');
}

createRoot(rootElement).render(
  <StrictMode>
    <BrowserRouter>
      <AppProviders>
        <AppErrorBoundary>
          <App />
        </AppErrorBoundary>
      </AppProviders>
    </BrowserRouter>
  </StrictMode>,
);
`;
}

export function getViteConfigTemplate(rtl: boolean): string {
  const vendorDependencies = rtl
    ? '["react", "react-dom", "react-router"]'
    : '["react", "react-dom", "react-router"]';

  return `import path from "node:path";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  optimizeDeps: {
    include: ${vendorDependencies},
  },
  server: {
    port: 3000,
    hmr: {
      overlay: true,
    },
  },
});
`;
}
