function getMetadataTemplate(projectName: string, rtl: boolean): string {
  const description = `Starter app generated by Forge for ${projectName}.`;
  const openGraphLocale = rtl
    ? `,
    locale: "en_US",
    alternateLocale: "ar_AR"`
    : "";

  return `export const metadata: Metadata = {
  title: "${projectName}",
  description: "${description}",
  robots: {
    index: true,
    follow: true
  },
  openGraph: {
    title: "${projectName}",
    description: "${description}",
    type: "website"${openGraphLocale}
  },
  twitter: {
    card: "summary_large_image",
    title: "${projectName}",
    description: "${description}"
  }
};
`;
}

function getLayoutBodyTemplate(childrenExpression: string): string {
  return `<body
        className={cn("antialiased", "font-sans", geist.variable, fontMono.variable)}
        suppressHydrationWarning
      >
        ${childrenExpression}
      </body>`;
}

export function getRootLayoutTemplate(rtl: boolean, projectName: string): string {
  if (!rtl) {
    return `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { AppProviders } from "@/components/app-providers";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-sans"
});

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono"
});

${getMetadataTemplate(projectName, false)}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      ${getLayoutBodyTemplate("<ThemeProvider><AppProviders>{children}</AppProviders></ThemeProvider>")}
    </html>
  );
}
`;
  }

  return `import { headers } from "next/headers";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { type Locale, defaultLocale, getDirectionForLocale, isLocale } from "@/lib/i18n";
import { cn } from "@/lib/utils";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-sans"
});

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono"
});

${getMetadataTemplate(projectName, true)}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const requestHeaders = await headers();
  const headerLocale = requestHeaders.get("x-forge-locale") ?? undefined;
  const initialLocale: Locale = isLocale(headerLocale) ? headerLocale : defaultLocale;
  const initialDirection = getDirectionForLocale(initialLocale);

  return (
    <html
      lang={initialLocale}
      dir={initialDirection}
      suppressHydrationWarning
    >
      ${getLayoutBodyTemplate("<ThemeProvider>{children}</ThemeProvider>")}
    </html>
  );
}
`;
}

export function getLocaleLayoutTemplate(): string {
  return `import { notFound } from "next/navigation";

import { AppProviders } from "@/components/app-providers";
import { type Locale, isLocale, locales } from "@/lib/i18n";

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!isLocale(locale)) {
    notFound();
  }

  return <AppProviders locale={locale as Locale}>{children}</AppProviders>;
}
`;
}

export function getPageTemplate(): string {
  return `import { StarterShell } from "@/components/starter-shell";

export default function Page() {
  return <StarterShell />;
}
`;
}

export function getProxyTemplate(): string {
  return `import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

import { defaultLocale, isLocale, locales } from "./lib/i18n";

function getPreferredLocale(request: NextRequest) {
  const acceptLanguage = request.headers.get("accept-language")?.toLowerCase() ?? "";

  for (const locale of locales) {
    if (acceptLanguage.includes(locale)) {
      return locale;
    }
  }

  return defaultLocale;
}

function withLocaleHeader(request: NextRequest, locale: string) {
  const requestHeaders = new Headers(request.headers);
  requestHeaders.set("x-forge-locale", locale);

  return NextResponse.next({
    request: {
      headers: requestHeaders
    }
  });
}

export function proxy(request: NextRequest) {
  const segments = request.nextUrl.pathname.split("/").filter(Boolean);
  const routeLocale = segments.length > 0 && isLocale(segments[0]) ? segments[0] : null;

  if (request.nextUrl.pathname === "/") {
    return NextResponse.redirect(new URL(\`/\${getPreferredLocale(request)}\`, request.url));
  }

  if (routeLocale) {
    return withLocaleHeader(request, routeLocale);
  }

  return NextResponse.next();
}

export const config = {
  matcher: ["/", "/(en|ar)/:path*"]
};
`;
}

export function getNotFoundTemplate(rtl: boolean): string {
  if (!rtl) {
    return `import { FallbackActions } from "@/components/fallback-actions";
import { FallbackScreen } from "@/components/fallback-screen";

export default function NotFound() {
  return (
    <FallbackScreen
      title="Page not found."
      description="This route does not exist yet."
      action={<FallbackActions homeHref="/" homeLabel="Go home" />}
    />
  );
}
`;
  }

  return `import { headers } from "next/headers";

import { FallbackActions } from "@/components/fallback-actions";
import { FallbackScreen } from "@/components/fallback-screen";
import { defaultLocale, isLocale } from "@/lib/i18n";

const MESSAGES = {
  en: {
    title: "Page not found.",
    description: "This route does not exist yet.",
    homeLabel: "Go home"
  },
  ar: {
    title: "الصفحة غير موجودة.",
    description: "هذا المسار غير موجود بعد.",
    homeLabel: "العودة للرئيسية"
  }
} as const;

export default async function NotFound() {
  const requestHeaders = await headers();
  const headerLocale = requestHeaders.get("x-forge-locale") ?? undefined;
  const locale = isLocale(headerLocale) ? headerLocale : defaultLocale;
  const copy = MESSAGES[locale];

  return (
    <FallbackScreen
      title={copy.title}
      description={copy.description}
      action={<FallbackActions homeHref={\`/\${locale}\`} homeLabel={copy.homeLabel} />}
    />
  );
}
`;
}

export function getErrorTemplate(rtl: boolean): string {
  if (!rtl) {
    return `"use client";

import { FallbackActions } from "@/components/fallback-actions";
import { ErrorView } from "@/components/error-view";

export default function RouteErrorBoundary({
  reset
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  return (
    <ErrorView
      title="Something went wrong."
      description="An unexpected error occurred. Please try again."
      action={<FallbackActions homeHref="/" homeLabel="Go home" retryLabel="Try again" onRetry={reset} />}
    />
  );
}
`;
  }

  return `"use client";

import { useParams } from "next/navigation";

import { FallbackActions } from "@/components/fallback-actions";
import { ErrorView } from "@/components/error-view";

const MESSAGES = {
  en: {
    homeLabel: "Go home",
    retryLabel: "Try again"
  },
  ar: {
    homeLabel: "العودة للرئيسية",
    retryLabel: "أعد المحاولة"
  }
} as const;

export default function RouteErrorBoundary({
  reset
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  const params = useParams<{ locale?: string }>();
  const locale = params.locale === "ar" ? "ar" : "en";
  const copy = MESSAGES[locale];

  return (
    <ErrorView
      title={locale === "ar" ? "حدث خطأ ما." : "Something went wrong."}
      description={
        locale === "ar"
          ? "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى."
          : "An unexpected error occurred. Please try again."
      }
      action={
        <FallbackActions
          homeHref={\`/\${locale}\`}
          homeLabel={copy.homeLabel}
          retryLabel={copy.retryLabel}
          onRetry={reset}
        />
      }
    />
  );
}
`;
}

export function getGlobalErrorTemplate(): string {
  return `"use client";

import "./globals.css";

import * as React from "react";
import { ErrorView } from "@/components/error-view";
import { FallbackActions } from "@/components/fallback-actions";
import { Geist, Geist_Mono } from "next/font/google";

import { cn } from "@/lib/utils";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-sans"
});

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono"
});

export default function GlobalError({
  reset
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  const [locale, setLocale] = React.useState<"en" | "ar">("en");

  React.useEffect(() => {
    setLocale(document.documentElement.lang === "ar" ? "ar" : "en");
  }, []);

  const copy =
    locale === "ar"
      ? {
          homeLabel: "العودة للرئيسية",
          retryLabel: "أعد المحاولة",
          homeHref: "/ar"
        }
      : {
          homeLabel: "Go home",
          retryLabel: "Try again",
          homeHref: "/"
        };

  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <body
        className={cn("antialiased", "font-sans", geist.variable, fontMono.variable)}
        suppressHydrationWarning
      >
        <ErrorView
          title={locale === "ar" ? "حدث خطأ ما." : "Something went wrong."}
          description={
            locale === "ar"
              ? "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى."
              : "An unexpected error occurred. Please try again."
          }
          action={
            <FallbackActions
              homeHref={copy.homeHref}
              homeLabel={copy.homeLabel}
              retryLabel={copy.retryLabel}
              onRetry={reset}
            />
          }
        />
      </body>
    </html>
  );
}
`;
}

export function getI18nTemplate(rtl: boolean): string {
  if (!rtl) {
    return `export const locales = ["en"] as const;
export const defaultLocale = "en";

export type Locale = (typeof locales)[number];
export type Direction = "ltr" | "rtl";

export function isLocale(value: string | undefined): value is Locale {
  return value === "en";
}

export function getDirectionForLocale(_locale: Locale): Direction {
  return "ltr";
}

export function getAlternateLocale(locale: Locale): Locale {
  return locale;
}

export function getLocaleHref(pathname: string, _locale: Locale): string {
  return pathname;
}
`;
  }

  return `export const locales = ["en", "ar"] as const;
export const defaultLocale = "en";

export type Locale = (typeof locales)[number];
export type Direction = "ltr" | "rtl";

export function isLocale(value: string | undefined): value is Locale {
  return value === "en" || value === "ar";
}

export function getDirectionForLocale(locale: Locale): Direction {
  return locale === "ar" ? "rtl" : "ltr";
}

export function getAlternateLocale(locale: Locale): Locale {
  return locale === "ar" ? "en" : "ar";
}

export function getLocaleHref(pathname: string, locale: Locale): string {
  const segments = pathname.split("/").filter(Boolean);

  if (segments.length > 0 && isLocale(segments[0])) {
    segments[0] = locale;
    return \`/\${segments.join("/")}\`;
  }

  return pathname === "/" ? \`/\${locale}\` : \`/\${locale}\${pathname}\`;
}
`;
}

export function getNextConfigTemplate(): string {
  return `import path from "node:path";
import { fileURLToPath } from "node:url";

const currentDirectory = path.dirname(fileURLToPath(import.meta.url));

/** @type {import("next").NextConfig} */
const nextConfig = {
  turbopack: {
    root: currentDirectory
  }
};

export default nextConfig;
`;
}
