function getMetadataTemplate(projectName: string, rtl: boolean): string {
  const description = `Starter app generated by Forge for ${projectName}.`;
  const openGraphLocale = rtl
    ? `,
    locale: "en_US",
    alternateLocale: "ar_AR"`
    : "";

  return `export const metadata: Metadata = {
  title: "${projectName}",
  description: "${description}",
  robots: {
    index: true,
    follow: true
  },
  openGraph: {
    title: "${projectName}",
    description: "${description}",
    type: "website"${openGraphLocale}
  },
  twitter: {
    card: "summary_large_image",
    title: "${projectName}",
    description: "${description}"
  }
};
`;
}

function getLayoutBodyTemplate(childrenExpression: string): string {
  return `<body
        className={cn("antialiased", "font-sans", geist.variable, fontMono.variable)}
        suppressHydrationWarning
      >
        ${childrenExpression}
      </body>`;
}

export function getRootLayoutTemplate(rtl: boolean, projectName: string): string {
  if (!rtl) {
    return `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { AppProviders } from "@/components/app-providers";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-sans"
});

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono"
});

${getMetadataTemplate(projectName, false)}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      ${getLayoutBodyTemplate("<ThemeProvider><AppProviders>{children}</AppProviders></ThemeProvider>")}
    </html>
  );
}
`;
  }

  return `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-sans"
});

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono"
});

${getMetadataTemplate(projectName, true)}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      ${getLayoutBodyTemplate("<ThemeProvider>{children}</ThemeProvider>")}
    </html>
  );
}
`;
}

export function getLocaleLayoutTemplate(): string {
  return `import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";

import { AppProviders } from "@/components/app-providers";
import { routing } from "@/i18n/routing";
import { getDirectionForLocale } from "@/lib/i18n";

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);
  const messages = await getMessages();
  const direction = getDirectionForLocale(locale);

  return (
    <NextIntlClientProvider messages={messages}>
      <div lang={locale} dir={direction}>
        <AppProviders>{children}</AppProviders>
      </div>
    </NextIntlClientProvider>
  );
}
`;
}

export function getPageTemplate(rtl: boolean): string {
  if (!rtl) {
    return `import { StarterShell } from "@/components/starter-shell";

export default function Page() {
  return <StarterShell />;
}
`;
  }

  return `import { setRequestLocale } from "next-intl/server";

import { StarterShell } from "@/components/starter-shell";

export default async function Page({
  params
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  setRequestLocale(locale);

  return <StarterShell />;
}
`;
}

export function getRoutingTemplate(): string {
  return `import { defineRouting } from "next-intl/routing";

export const routing = defineRouting({
  locales: ["en", "ar"],
  defaultLocale: "en"
});

export type Locale = (typeof routing.locales)[number];
`;
}

export function getRequestTemplate(): string {
  return `import { hasLocale } from "next-intl";
import { getRequestConfig } from "next-intl/server";

import { routing } from "./routing";

export default getRequestConfig(async ({ requestLocale }) => {
  const requested = await requestLocale;
  const locale = hasLocale(routing.locales, requested)
    ? requested
    : routing.defaultLocale;

  return {
    locale,
    messages: (await import(\`../messages/\${locale}.json\`)).default
  };
});
`;
}

export function getNavigationTemplate(): string {
  return `import { createNavigation } from "next-intl/navigation";

import { routing } from "./routing";

export const { Link, redirect, usePathname, useRouter, getPathname } =
  createNavigation(routing);
`;
}

export function getMessagesTemplate(locale: "en" | "ar"): string {
  if (locale === "en") {
    return `{
  "StarterShell": {
    "eyebrow": "Forge",
    "heading": "Your starter is ready to customize.",
    "description": "Replace this screen in app/[locale]/page.tsx. Edit components/ for UI pieces, app-providers.tsx for shared providers, or messages/ for translated copy."
  },
  "ThemeToggle": {
    "fallbackLabel": "Theme",
    "toLightLabel": "Light",
    "toDarkLabel": "Dark"
  },
  "LanguageToggle": {
    "label": "Arabic"
  },
  "Fallback": {
    "eyebrow": "Forge",
    "notFoundTitle": "Page not found.",
    "notFoundDescription": "This route does not exist yet.",
    "errorTitle": "Something went wrong.",
    "errorDescription": "An unexpected error occurred. Please try again.",
    "homeLabel": "Go home",
    "retryLabel": "Try again"
  }
}
`;
  }

  return `{
  "StarterShell": {
    "eyebrow": "فورج",
    "heading": "الواجهة جاهزة لتبدأ التعديل.",
    "description": "استبدل هذه الشاشة من app/[locale]/page.tsx. عدل components/ لعناصر الواجهة، أو app-providers.tsx للمزودات المشتركة، أو messages/ للنصوص المترجمة."
  },
  "ThemeToggle": {
    "fallbackLabel": "المظهر",
    "toLightLabel": "فاتح",
    "toDarkLabel": "داكن"
  },
  "LanguageToggle": {
    "label": "English"
  },
  "Fallback": {
    "eyebrow": "فورج",
    "notFoundTitle": "الصفحة غير موجودة.",
    "notFoundDescription": "هذا المسار غير موجود بعد.",
    "errorTitle": "حدث خطأ ما.",
    "errorDescription": "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",
    "homeLabel": "العودة للرئيسية",
    "retryLabel": "أعد المحاولة"
  }
}
`;
}

export function getProxyTemplate(): string {
  return `import createMiddleware from "next-intl/middleware";

import { routing } from "./i18n/routing";

export const proxy = createMiddleware(routing);

export const config = {
  matcher: "/((?!api|trpc|_next|_vercel|.*\\\\..*).*)"
};
`;
}

export function getNotFoundTemplate(rtl: boolean): string {
  if (!rtl) {
    return `import { FallbackActions } from "@/components/fallback-actions";
import { FallbackScreen } from "@/components/fallback-screen";

export default function NotFound() {
  return (
    <FallbackScreen
      title="Page not found."
      description="This route does not exist yet."
      action={<FallbackActions homeHref="/" homeLabel="Go home" />}
    />
  );
}
`;
  }

  return `import { getLocale, getTranslations } from "next-intl/server";

import { FallbackActions } from "@/components/fallback-actions";
import { FallbackScreen } from "@/components/fallback-screen";
import { getDirectionForLocale, isLocale } from "@/lib/i18n";

export default async function NotFound() {
  const requestLocale = await getLocale();
  const locale = isLocale(requestLocale) ? requestLocale : "en";
  const direction = getDirectionForLocale(locale);
  const t = await getTranslations("Fallback");

  return (
    <FallbackScreen
      eyebrow={t("eyebrow")}
      locale={locale}
      direction={direction}
      title={t("notFoundTitle")}
      description={t("notFoundDescription")}
      action={<FallbackActions homeHref={\`/\${locale}\`} homeLabel={t("homeLabel")} />}
    />
  );
}
`;
}

export function getLocaleNotFoundTemplate(): string {
  return `import { getLocale, getTranslations } from "next-intl/server";

import { FallbackActions } from "@/components/fallback-actions";
import { FallbackScreen } from "@/components/fallback-screen";
import { getDirectionForLocale, isLocale } from "@/lib/i18n";

export default async function LocaleNotFound() {
  const requestLocale = await getLocale();
  const locale = isLocale(requestLocale) ? requestLocale : "en";
  const direction = getDirectionForLocale(locale);
  const t = await getTranslations("Fallback");

  return (
    <FallbackScreen
      eyebrow={t("eyebrow")}
      locale={locale}
      direction={direction}
      title={t("notFoundTitle")}
      description={t("notFoundDescription")}
      action={<FallbackActions homeHref={\`/\${locale}\`} homeLabel={t("homeLabel")} />}
    />
  );
}
`;
}

export function getErrorTemplate(rtl: boolean): string {
  if (!rtl) {
    return `"use client";

import { FallbackActions } from "@/components/fallback-actions";
import { ErrorView } from "@/components/error-view";

export default function RouteErrorBoundary({
  reset
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  return (
    <ErrorView
      title="Something went wrong."
      description="An unexpected error occurred. Please try again."
      action={<FallbackActions homeHref="/" homeLabel="Go home" retryLabel="Try again" onRetry={reset} />}
    />
  );
}
`;
  }

  return `"use client";

import { FallbackActions } from "@/components/fallback-actions";
import { ErrorView } from "@/components/error-view";

export default function RouteErrorBoundary({
  reset
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  return (
    <ErrorView
      title="Something went wrong."
      description="An unexpected error occurred. Please try again."
      action={<FallbackActions homeHref="/" homeLabel="Go home" retryLabel="Try again" onRetry={reset} />}
    />
  );
}
`;
}

export function getLocaleErrorTemplate(): string {
  return `"use client";

import { useLocale, useTranslations } from "next-intl";

import { FallbackActions } from "@/components/fallback-actions";
import { ErrorView } from "@/components/error-view";
import { type Locale, getDirectionForLocale } from "@/lib/i18n";

export default function LocaleErrorBoundary({
  reset
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  const locale = useLocale() as Locale;
  const direction = getDirectionForLocale(locale);
  const t = useTranslations("Fallback");

  return (
    <ErrorView
      eyebrow={t("eyebrow")}
      locale={locale}
      direction={direction}
      title={t("errorTitle")}
      description={t("errorDescription")}
      action={
        <FallbackActions
          homeHref={\`/\${locale}\`}
          homeLabel={t("homeLabel")}
          retryLabel={t("retryLabel")}
          onRetry={reset}
        />
      }
    />
  );
}
`;
}

export function getGlobalErrorTemplate(): string {
  return `"use client";

import "./globals.css";

import * as React from "react";
import { Geist, Geist_Mono } from "next/font/google";

import { ErrorView } from "@/components/error-view";
import { FallbackActions } from "@/components/fallback-actions";
import { type Direction } from "@/lib/i18n";
import { cn } from "@/lib/utils";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-sans"
});

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono"
});

type LocaleCopy = {
  locale: "en" | "ar";
  direction: Direction;
  eyebrow: string;
  title: string;
  description: string;
  homeLabel: string;
  retryLabel: string;
  homeHref: string;
};

const ENGLISH_COPY: LocaleCopy = {
  locale: "en",
  direction: "ltr",
  eyebrow: "Forge",
  title: "Something went wrong.",
  description: "An unexpected error occurred. Please try again.",
  homeLabel: "Go home",
  retryLabel: "Try again",
  homeHref: "/en"
};

const ARABIC_COPY: LocaleCopy = {
  locale: "ar",
  direction: "rtl",
  eyebrow: "فورج",
  title: "حدث خطأ ما.",
  description: "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",
  homeLabel: "العودة للرئيسية",
  retryLabel: "أعد المحاولة",
  homeHref: "/ar"
};

export default function GlobalError({
  reset
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  const [copy, setCopy] = React.useState<LocaleCopy>(ENGLISH_COPY);

  React.useEffect(() => {
    setCopy(document.documentElement.lang === "ar" ? ARABIC_COPY : ENGLISH_COPY);
  }, []);

  return (
    <html lang={copy.locale} dir={copy.direction} suppressHydrationWarning>
      <body
        className={cn("antialiased", "font-sans", geist.variable, fontMono.variable)}
        suppressHydrationWarning
      >
        <ErrorView
          eyebrow={copy.eyebrow}
          locale={copy.locale}
          direction={copy.direction}
          title={copy.title}
          description={copy.description}
          action={
            <FallbackActions
              homeHref={copy.homeHref}
              homeLabel={copy.homeLabel}
              retryLabel={copy.retryLabel}
              onRetry={reset}
            />
          }
        />
      </body>
    </html>
  );
}
`;
}

export function getI18nTemplate(rtl: boolean): string {
  if (!rtl) {
    return `export type Locale = "en";
export type Direction = "ltr" | "rtl";

export function isLocale(value: string | undefined): value is Locale {
  return value === "en";
}

export function getDirectionForLocale(_locale: Locale): Direction {
  return "ltr";
}

export function getAlternateLocale(locale: Locale): Locale {
  return locale;
}
`;
  }

  return `import type { Locale as RoutingLocale } from "@/i18n/routing";
import { routing } from "@/i18n/routing";

export type Locale = RoutingLocale;
export type Direction = "ltr" | "rtl";

export function isLocale(value: string | undefined): value is Locale {
  return routing.locales.some((locale) => locale === value);
}

export function getDirectionForLocale(locale: Locale): Direction {
  return locale === "ar" ? "rtl" : "ltr";
}

export function getAlternateLocale(locale: Locale): Locale {
  return locale === "ar" ? "en" : "ar";
}
`;
}

export function getNextConfigTemplate(rtl: boolean): string {
  if (!rtl) {
    return `import path from "node:path";
import { fileURLToPath } from "node:url";

const currentDirectory = path.dirname(fileURLToPath(import.meta.url));

/** @type {import("next").NextConfig} */
const nextConfig = {
  turbopack: {
    root: currentDirectory
  }
};

export default nextConfig;
`;
  }

  return `import path from "node:path";
import { fileURLToPath } from "node:url";
import createNextIntlPlugin from "next-intl/plugin";

const currentDirectory = path.dirname(fileURLToPath(import.meta.url));

/** @type {import("next").NextConfig} */
const nextConfig = {
  turbopack: {
    root: currentDirectory
  }
};

const withNextIntl = createNextIntlPlugin("./i18n/request.ts");

export default withNextIntl(nextConfig);
`;
}
