import {
  HeadContent,
  ScriptOnce,
  Scripts,
  createRootRoute,
  useParams,
} from "@tanstack/react-router"
import { useTranslation } from "react-i18next"
import appCss from "../styles.css?url"
import type * as React from "react"

import { AppProviders } from "@/components/app-providers"
import { FallbackActions } from "@/components/fallback-actions"
import { FallbackScreen } from "@/components/fallback-screen"
import { RouteError } from "@/components/route-error"
import { useRouteLocale } from "@/hooks/use-route-locale"
import { defaultLocale, getLocaleHref, isLocale } from "@/lib/i18n"

export const Route = createRootRoute({
  head: () => ({
    meta: [
      {
        charSet: "utf-8",
      },
      {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
      },
      {
        title: "forge-start-radix-rtl-fixture",
      },
      {
        name: "description",
        content: "Starter app generated by Forge for forge-start-radix-rtl-fixture.",
      },
      {
        name: "robots",
        content: "index, follow",
      },
      {
        property: "og:locale",
        content: "en_US",
      },
      {
        property: "og:locale:alternate",
        content: "ar_AR",
      },
      {
        property: "og:title",
        content: "forge-start-radix-rtl-fixture",
      },
      {
        property: "og:description",
        content: "Starter app generated by Forge for forge-start-radix-rtl-fixture.",
      },
      {
        property: "og:type",
        content: "website",
      },
      {
        name: "twitter:card",
        content: "summary_large_image",
      },
      {
        name: "twitter:title",
        content: "forge-start-radix-rtl-fixture",
      },
      {
        name: "twitter:description",
        content: "Starter app generated by Forge for forge-start-radix-rtl-fixture.",
      },
    ],
    links: [
      {
        rel: "icon",
        href: "/favicon.ico",
        sizes: "any",
        type: "image/x-icon",
      },
      {
        rel: "shortcut icon",
        href: "/favicon.ico",
        type: "image/x-icon",
      },
      {
        rel: "manifest",
        href: "/site.webmanifest",
      },
      {
        rel: "stylesheet",
        href: appCss,
      },
    ],
  }),
  errorComponent: RootErrorScreen,
  shellComponent: RootDocument,
  notFoundComponent: RootNotFoundScreen,
})

function RootDocument({ children }: { children: React.ReactNode }) {
  const params = useParams({ strict: false })
  const locale = isLocale(params.locale) ? params.locale : defaultLocale

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"} suppressHydrationWarning>
      <head>
        <meta name="color-scheme" content="dark light" />
        <HeadContent />
      </head>
      <body className="min-h-svh bg-background font-sans text-foreground antialiased">
        <ScriptOnce>
          {
            '(function(){try{var root=document.documentElement;var stored=localStorage.getItem("theme");var theme=stored==="light"||stored==="dark"||stored==="system"?stored:"system";var resolved=theme==="system"?(window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"):theme;root.classList.remove("light","dark");root.classList.add(resolved);root.style.colorScheme=resolved;}catch(_error){}})();'
          }
        </ScriptOnce>
        <AppProviders locale={locale}>{children}</AppProviders>
        <Scripts />
      </body>
    </html>
  )
}

function RootNotFoundScreen() {
  const { t } = useTranslation()
  const { direction, locale } = useRouteLocale()

  return (
    <FallbackScreen
      eyebrow={t("Fallback.eyebrow")}
      locale={locale}
      direction={direction}
      title={t("Fallback.notFoundTitle")}
      description={t("Fallback.notFoundDescription")}
      action={
        <FallbackActions
          homeHref={getLocaleHref("/", locale)}
          homeLabel={t("Fallback.homeLabel")}
        />
      }
    />
  )
}

function RootErrorScreen({ reset }: { error: unknown; reset: () => void }) {
  return <RouteError onRetry={reset} />
}
