import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import "./globals.css"
import { AppProviders } from "@/components/app-providers"
import { ThemeProvider } from "@/components/theme-provider"
import { cn } from "@/lib/utils"

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
})

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

export const metadata: Metadata = {
  title: "forge-next-base-ltr-fixture",
  description: "Starter app generated by Forge for forge-next-base-ltr-fixture.",
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    title: "forge-next-base-ltr-fixture",
    description: "Starter app generated by Forge for forge-next-base-ltr-fixture.",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "forge-next-base-ltr-fixture",
    description: "Starter app generated by Forge for forge-next-base-ltr-fixture.",
  },
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <body
        className={cn("antialiased", "font-sans", geist.variable, fontMono.variable)}
        suppressHydrationWarning
      >
        <ThemeProvider>
          <AppProviders>{children}</AppProviders>
        </ThemeProvider>
      </body>
    </html>
  )
}
