import { getThemeBootstrapScript } from "../shared/theme-bootstrap.js";

export function getRootRouteTemplate(
  projectName: string,
  rtl: boolean,
): string {
  const themeBootstrapScript = JSON.stringify(getThemeBootstrapScript());
  const description = `Starter app generated by Forge for ${projectName}.`;
  const ogLocaleMetaTags = rtl
    ? `      {
        property: "og:locale",
        content: "en_US",
      },
      {
        property: "og:locale:alternate",
        content: "ar_AR",
      },
`
    : "";

  if (!rtl) {
    return `import { HeadContent, ScriptOnce, Scripts, createRootRoute, useLocation, useNavigate } from "@tanstack/react-router";
import appCss from "../styles.css?url";
import type * as React from "react";
import { AppProviders } from "@/components/app-providers";
import { Button } from "@/components/ui/button";
import { FallbackScreen } from "@/components/fallback-screen";
import { useUiSound } from "@/hooks/use-ui-sound";
import { RouteError } from "@/components/route-error";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      {
        charSet: "utf-8",
      },
      {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
      },
      {
        title: "${projectName}",
      },
      {
        name: "description",
        content: "${description}",
      },
      {
        name: "robots",
        content: "index, follow",
      },
${ogLocaleMetaTags}      {
        property: "og:title",
        content: "${projectName}",
      },
      {
        property: "og:description",
        content: "${description}",
      },
      {
        property: "og:type",
        content: "website",
      },
      {
        name: "twitter:card",
        content: "summary_large_image",
      },
      {
        name: "twitter:title",
        content: "${projectName}",
      },
      {
        name: "twitter:description",
        content: "${description}",
      },
    ],
    links: [
      {
        rel: "icon",
        href: "/favicon.ico",
        sizes: "any",
        type: "image/x-icon",
      },
      {
        rel: "shortcut icon",
        href: "/favicon.ico",
        type: "image/x-icon",
      },
      {
        rel: "manifest",
        href: "/site.webmanifest",
      },
      {
        rel: "stylesheet",
        href: appCss,
      },
    ],
  }),
  errorComponent: RootErrorScreen,
  shellComponent: RootDocument,
  notFoundComponent: NotFoundScreen,
});

function RootDocument({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <head>
        <meta name="color-scheme" content="dark light" />
        <HeadContent />
      </head>
      <body className="min-h-svh bg-background font-sans text-foreground antialiased">
        <ScriptOnce>{${themeBootstrapScript}}</ScriptOnce>
        <AppProviders>{children}</AppProviders>
        <Scripts />
      </body>
    </html>
  );
}

function NotFoundScreen() {
  const location = useLocation();
  const navigate = useNavigate();
  const { playSound } = useUiSound();
  const copy =
    location.pathname.split("/").filter(Boolean)[0] === "ar"
      ? {
          title: "الصفحة غير موجودة.",
          description: "هذا المسار غير موجود بعد في الواجهة المولدة.",
          backLabel: "الرجوع",
          homeLabel: "العودة للرئيسية"
        }
      : {
          title: "Page not found.",
          description: "This route does not exist in the generated starter yet.",
          backLabel: "Go back",
          homeLabel: "Go home"
        };
  const segments = location.pathname.split("/").filter(Boolean);
  const homeHref = segments.length > 0 && (segments[0] === "en" || segments[0] === "ar") ? \`/\${segments[0]}\` : "/";

  return (
    <FallbackScreen
      title={copy.title}
      description={copy.description}
      action={
        <>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="h-9 rounded-full px-3"
            onClick={() => {
              playSound("click-soft");
              window.history.back();
            }}
          >
            {copy.backLabel}
          </Button>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="h-9 rounded-full px-3"
            onClick={() => {
              playSound("click-soft");
              navigate({ to: homeHref });
            }}
          >
            {copy.homeLabel}
          </Button>
        </>
      }
    />
  );
}

function RootErrorScreen({ reset }: { error: unknown; reset: () => void }) {
  return <RouteError onRetry={reset} />;
}
`;
  }

  return `import {
  HeadContent,
  ScriptOnce,
  Scripts,
  createRootRoute,
  useLocation,
  useNavigate,
  useParams,
} from "@tanstack/react-router";
import appCss from "../styles.css?url";
import type * as React from "react";
import { AppProviders } from "@/components/app-providers";
import { Button } from "@/components/ui/button";
import { FallbackScreen } from "@/components/fallback-screen";
import { useUiSound } from "@/hooks/use-ui-sound";
import { RouteError } from "@/components/route-error";
import { defaultLocale, getDirectionForLocale, isLocale } from "@/lib/i18n";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      {
        charSet: "utf-8",
      },
      {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
      },
      {
        title: "${projectName}",
      },
      {
        name: "description",
        content: "${description}",
      },
      {
        name: "robots",
        content: "index, follow",
      },
${ogLocaleMetaTags}      {
        property: "og:title",
        content: "${projectName}",
      },
      {
        property: "og:description",
        content: "${description}",
      },
      {
        property: "og:type",
        content: "website",
      },
      {
        name: "twitter:card",
        content: "summary_large_image",
      },
      {
        name: "twitter:title",
        content: "${projectName}",
      },
      {
        name: "twitter:description",
        content: "${description}",
      },
    ],
    links: [
      {
        rel: "icon",
        href: "/favicon.ico",
        sizes: "any",
        type: "image/x-icon",
      },
      {
        rel: "shortcut icon",
        href: "/favicon.ico",
        type: "image/x-icon",
      },
      {
        rel: "manifest",
        href: "/site.webmanifest",
      },
      {
        rel: "stylesheet",
        href: appCss,
      },
    ],
  }),
  errorComponent: RootErrorScreen,
  shellComponent: RootDocument,
  notFoundComponent: NotFoundScreen,
});

function RootDocument({ children }: { children: React.ReactNode }) {
  const params = useParams({ strict: false });
  const locale = isLocale(params.locale) ? params.locale : defaultLocale;
  const direction = getDirectionForLocale(locale);

  return (
    <html lang={locale} dir={direction} suppressHydrationWarning>
      <head>
        <meta name="color-scheme" content="dark light" />
        <HeadContent />
      </head>
      <body className="min-h-svh bg-background font-sans text-foreground antialiased">
        <ScriptOnce>{${themeBootstrapScript}}</ScriptOnce>
        <AppProviders locale={locale}>{children}</AppProviders>
        <Scripts />
      </body>
    </html>
  );
}

function NotFoundScreen() {
  const location = useLocation();
  const navigate = useNavigate();
  const { playSound } = useUiSound();
  const copy =
    location.pathname.split("/").filter(Boolean)[0] === "ar"
      ? {
          title: "الصفحة غير موجودة.",
          description: "هذا المسار غير موجود بعد في الواجهة المولدة.",
          backLabel: "الرجوع",
          homeLabel: "العودة للرئيسية"
        }
      : {
          title: "Page not found.",
          description: "This route does not exist in the generated starter yet.",
          backLabel: "Go back",
          homeLabel: "Go home"
        };
  const segments = location.pathname.split("/").filter(Boolean);
  const homeHref = segments.length > 0 && (segments[0] === "en" || segments[0] === "ar") ? \`/\${segments[0]}\` : "/";

  return (
    <FallbackScreen
      title={copy.title}
      description={copy.description}
      action={
        <>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="h-9 rounded-full px-3"
            onClick={() => {
              playSound("click-soft");
              window.history.back();
            }}
          >
            {copy.backLabel}
          </Button>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="h-9 rounded-full px-3"
            onClick={() => {
              playSound("click-soft");
              navigate({ to: homeHref });
            }}
          >
            {copy.homeLabel}
          </Button>
        </>
      }
    />
  );
}

function RootErrorScreen({ reset }: { error: unknown; reset: () => void }) {
  return <RouteError onRetry={reset} />;
}
`;
}

export function getIndexRouteTemplate(rtl: boolean): string {
  if (!rtl) {
    return `import { createFileRoute } from "@tanstack/react-router";

import { StarterShell } from "@/components/starter-shell";

export const Route = createFileRoute("/")({
  component: Page,
});

function Page() {
  return <StarterShell />;
}
`;
  }

  return `import { createFileRoute, redirect } from "@tanstack/react-router";

import { defaultLocale } from "@/lib/i18n";

export const Route = createFileRoute("/")({
  beforeLoad: () => {
    throw redirect({
      to: "/$locale",
      params: {
        locale: defaultLocale,
      },
    });
  },
});
`;
}

export function getLocaleLayoutRouteTemplate(): string {
  return `import { Outlet, createFileRoute, notFound, useLocation, useNavigate } from "@tanstack/react-router";

import { Button } from "@/components/ui/button";
import { FallbackScreen } from "@/components/fallback-screen";
import { useUiSound } from "@/hooks/use-ui-sound";
import { isLocale } from "@/lib/i18n";

export const Route = createFileRoute("/$locale")({
  beforeLoad: ({ params }) => {
    if (!isLocale(params.locale)) {
      throw notFound();
    }
  },
  notFoundComponent: LocaleNotFoundScreen,
  component: LocaleLayout,
});

function LocaleLayout() {
  return <Outlet />;
}

function LocaleNotFoundScreen() {
  const location = useLocation();
  const navigate = useNavigate();
  const { playSound } = useUiSound();
  const routeLocale = location.pathname.split("/").filter(Boolean)[0];
  const copy =
    routeLocale === "ar"
      ? {
          title: "الصفحة غير موجودة.",
          description: "هذا المسار غير موجود بعد في الواجهة المولدة.",
          backLabel: "الرجوع",
          homeLabel: "العودة للرئيسية"
        }
      : {
          title: "Page not found.",
          description: "This route does not exist in the generated starter yet.",
          backLabel: "Go back",
          homeLabel: "Go home"
        };
  const homeHref = routeLocale === "ar" || routeLocale === "en" ? \`/\${routeLocale}\` : "/";

  return (
    <FallbackScreen
      title={copy.title}
      description={copy.description}
      action={
        <>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="h-9 rounded-full px-3"
            onClick={() => {
              playSound("click-soft");
              window.history.back();
            }}
          >
            {copy.backLabel}
          </Button>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="h-9 rounded-full px-3"
            onClick={() => {
              playSound("click-soft");
              navigate({ to: homeHref });
            }}
          >
            {copy.homeLabel}
          </Button>
        </>
      }
    />
  );
}
`;
}

export function getLocaleIndexRouteTemplate(): string {
  return `import { createFileRoute } from "@tanstack/react-router";

import { StarterShell } from "@/components/starter-shell";

export const Route = createFileRoute("/$locale/")({
  component: Page,
});

function Page() {
  return <StarterShell />;
}
`;
}

export function getI18nTemplate(rtl: boolean): string {
  if (!rtl) {
    return `export const locales = ["en"] as const;
export const defaultLocale = "en";

export type Locale = (typeof locales)[number];
export type Direction = "ltr" | "rtl";

export function isLocale(value: string | undefined): value is Locale {
  return value === "en";
}

export function getDirectionForLocale(_locale: Locale): Direction {
  return "ltr";
}

export function getAlternateLocale(locale: Locale): Locale {
  return locale;
}

export function getLocaleHref(pathname: string, _locale: Locale): string {
  return pathname;
}
`;
  }

  return `export const locales = ["en", "ar"] as const;
export const defaultLocale = "en";

export type Locale = (typeof locales)[number];
export type Direction = "ltr" | "rtl";

export function isLocale(value: string | undefined): value is Locale {
  return value === "en" || value === "ar";
}

export function getDirectionForLocale(locale: Locale): Direction {
  return locale === "ar" ? "rtl" : "ltr";
}

export function getAlternateLocale(locale: Locale): Locale {
  return locale === "ar" ? "en" : "ar";
}

export function getLocaleHref(pathname: string, locale: Locale): string {
  const segments = pathname.split("/").filter(Boolean);

  if (segments.length > 0 && isLocale(segments[0])) {
    segments[0] = locale;
    return \`/\${segments.join("/")}\`;
  }

  return pathname === "/" ? \`/\${locale}\` : \`/\${locale}\${pathname}\`;
}
`;
}

export function getViteConfigTemplate(): string {
  return `import { defineConfig } from "vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import viteReact from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { nitro } from "nitro/vite";

export default defineConfig({
  resolve: {
    tsconfigPaths: true,
  },
  plugins: [
    nitro(),
    tailwindcss(),
    tanstackStart(),
    viteReact(),
  ],
});
`;
}
