import { getThemeBootstrapScript } from "../shared/theme-bootstrap.js";

export function getRootRouteTemplate(
  projectName: string,
  rtl: boolean,
): string {
  const themeBootstrapScript = JSON.stringify(getThemeBootstrapScript());
  const description = `Starter app generated by Forge for ${projectName}.`;
  const ogLocaleMetaTags = rtl
    ? `      {
        property: "og:locale",
        content: "en_US",
      },
      {
        property: "og:locale:alternate",
        content: "ar_AR",
      },
`
    : "";

  if (!rtl) {
    return `import { HeadContent, ScriptOnce, Scripts, createRootRoute } from "@tanstack/react-router";
import appCss from "../styles.css?url";
import type * as React from "react";

import { AppProviders } from "@/components/app-providers";
import { FallbackActions } from "@/components/fallback-actions";
import { FallbackScreen } from "@/components/fallback-screen";
import { RouteError } from "@/components/route-error";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      {
        charSet: "utf-8",
      },
      {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
      },
      {
        title: "${projectName}",
      },
      {
        name: "description",
        content: "${description}",
      },
      {
        name: "robots",
        content: "index, follow",
      },
${ogLocaleMetaTags}      {
        property: "og:title",
        content: "${projectName}",
      },
      {
        property: "og:description",
        content: "${description}",
      },
      {
        property: "og:type",
        content: "website",
      },
      {
        name: "twitter:card",
        content: "summary_large_image",
      },
      {
        name: "twitter:title",
        content: "${projectName}",
      },
      {
        name: "twitter:description",
        content: "${description}",
      },
    ],
    links: [
      {
        rel: "icon",
        href: "/favicon.ico",
        sizes: "any",
        type: "image/x-icon",
      },
      {
        rel: "shortcut icon",
        href: "/favicon.ico",
        type: "image/x-icon",
      },
      {
        rel: "manifest",
        href: "/site.webmanifest",
      },
      {
        rel: "stylesheet",
        href: appCss,
      },
    ],
  }),
  errorComponent: RootErrorScreen,
  shellComponent: RootDocument,
  notFoundComponent: RootNotFoundScreen,
});

function RootDocument({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <head>
        <meta name="color-scheme" content="dark light" />
        <HeadContent />
      </head>
      <body className="min-h-svh bg-background font-sans text-foreground antialiased">
        <ScriptOnce>{${themeBootstrapScript}}</ScriptOnce>
        <AppProviders>{children}</AppProviders>
        <Scripts />
      </body>
    </html>
  );
}

function RootNotFoundScreen() {
  return (
    <FallbackScreen
      title="Page not found."
      description="This route does not exist yet."
      action={<FallbackActions homeHref="/" homeLabel="Go home" />}
    />
  );
}

function RootErrorScreen({ reset }: { error: unknown; reset: () => void }) {
  return <RouteError onRetry={reset} />;
}
`;
  }

  return `import {
  HeadContent,
  ScriptOnce,
  Scripts,
  createRootRoute,
  useParams,
} from "@tanstack/react-router";
import { useTranslation } from "react-i18next";
import appCss from "../styles.css?url";
import type * as React from "react";

import { AppProviders } from "@/components/app-providers";
import { FallbackActions } from "@/components/fallback-actions";
import { FallbackScreen } from "@/components/fallback-screen";
import { RouteError } from "@/components/route-error";
import { useRouteLocale } from "@/hooks/use-route-locale";
import { defaultLocale, getLocaleHref, isLocale } from "@/lib/i18n";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      {
        charSet: "utf-8",
      },
      {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
      },
      {
        title: "${projectName}",
      },
      {
        name: "description",
        content: "${description}",
      },
      {
        name: "robots",
        content: "index, follow",
      },
${ogLocaleMetaTags}      {
        property: "og:title",
        content: "${projectName}",
      },
      {
        property: "og:description",
        content: "${description}",
      },
      {
        property: "og:type",
        content: "website",
      },
      {
        name: "twitter:card",
        content: "summary_large_image",
      },
      {
        name: "twitter:title",
        content: "${projectName}",
      },
      {
        name: "twitter:description",
        content: "${description}",
      },
    ],
    links: [
      {
        rel: "icon",
        href: "/favicon.ico",
        sizes: "any",
        type: "image/x-icon",
      },
      {
        rel: "shortcut icon",
        href: "/favicon.ico",
        type: "image/x-icon",
      },
      {
        rel: "manifest",
        href: "/site.webmanifest",
      },
      {
        rel: "stylesheet",
        href: appCss,
      },
    ],
  }),
  errorComponent: RootErrorScreen,
  shellComponent: RootDocument,
  notFoundComponent: RootNotFoundScreen,
});

function RootDocument({ children }: { children: React.ReactNode }) {
  const params = useParams({ strict: false });
  const locale = isLocale(params.locale) ? params.locale : defaultLocale;

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"} suppressHydrationWarning>
      <head>
        <meta name="color-scheme" content="dark light" />
        <HeadContent />
      </head>
      <body className="min-h-svh bg-background font-sans text-foreground antialiased">
        <ScriptOnce>{${themeBootstrapScript}}</ScriptOnce>
        <AppProviders locale={locale}>{children}</AppProviders>
        <Scripts />
      </body>
    </html>
  );
}

function RootNotFoundScreen() {
  const { t } = useTranslation();
  const { direction, locale } = useRouteLocale();

  return (
    <FallbackScreen
      eyebrow={t("Fallback.eyebrow")}
      locale={locale}
      direction={direction}
      title={t("Fallback.notFoundTitle")}
      description={t("Fallback.notFoundDescription")}
      action={
        <FallbackActions
          homeHref={getLocaleHref("/", locale)}
          homeLabel={t("Fallback.homeLabel")}
        />
      }
    />
  );
}

function RootErrorScreen({ reset }: { error: unknown; reset: () => void }) {
  return <RouteError onRetry={reset} />;
}
`;
}

export function getIndexRouteTemplate(rtl: boolean): string {
  if (!rtl) {
    return `import { createFileRoute } from "@tanstack/react-router";

import { StarterShell } from "@/components/starter-shell";

export const Route = createFileRoute("/")({
  component: Page,
});

function Page() {
  return <StarterShell />;
}
`;
  }

  return `import { createFileRoute, redirect } from "@tanstack/react-router";

import { defaultLocale } from "@/lib/i18n";

export const Route = createFileRoute("/")({
  beforeLoad: () => {
    throw redirect({
      to: "/$locale",
      params: {
        locale: defaultLocale,
      },
    });
  },
});
`;
}

export function getLocaleLayoutRouteTemplate(): string {
  return `import { Outlet, createFileRoute, notFound } from "@tanstack/react-router";
import { useTranslation } from "react-i18next";

import { FallbackActions } from "@/components/fallback-actions";
import { FallbackScreen } from "@/components/fallback-screen";
import { useRouteLocale } from "@/hooks/use-route-locale";
import { getLocaleHref, isLocale } from "@/lib/i18n";

export const Route = createFileRoute("/$locale")({
  beforeLoad: ({ params }) => {
    if (!isLocale(params.locale)) {
      throw notFound();
    }
  },
  notFoundComponent: LocaleNotFoundScreen,
  component: LocaleLayout,
});

function LocaleLayout() {
  return <Outlet />;
}

function LocaleNotFoundScreen() {
  const { t } = useTranslation();
  const { direction, locale } = useRouteLocale();

  return (
    <FallbackScreen
      eyebrow={t("Fallback.eyebrow")}
      locale={locale}
      direction={direction}
      title={t("Fallback.notFoundTitle")}
      description={t("Fallback.notFoundDescription")}
      action={
        <FallbackActions
          homeHref={getLocaleHref("/", locale)}
          homeLabel={t("Fallback.homeLabel")}
        />
      }
    />
  );
}
`;
}

export function getLocaleIndexRouteTemplate(): string {
  return `import { createFileRoute } from "@tanstack/react-router";

import { StarterShell } from "@/components/starter-shell";

export const Route = createFileRoute("/$locale/")({
  component: Page,
});

function Page() {
  return <StarterShell />;
}
`;
}

export function getI18nTemplate(rtl: boolean): string {
  if (!rtl) {
    return `export const locales = ["en"] as const;
export const defaultLocale = "en";

export type Locale = (typeof locales)[number];
export type Direction = "ltr" | "rtl";

export function isLocale(value: string | undefined): value is Locale {
  return value === "en";
}

export function getDirectionForLocale(_locale: Locale): Direction {
  return "ltr";
}

export function getAlternateLocale(locale: Locale): Locale {
  return locale;
}

export function getLocaleHref(pathname: string, _locale: Locale): string {
  return pathname;
}

export function getLocaleFromPathname(_pathname: string): Locale {
  return "en";
}
`;
  }

  return `export const locales = ["en", "ar"] as const;
export const defaultLocale = "en";

export type Locale = (typeof locales)[number];
export type Direction = "ltr" | "rtl";

export function isLocale(value: string | undefined): value is Locale {
  return value === "en" || value === "ar";
}

export function getDirectionForLocale(locale: Locale): Direction {
  return locale === "ar" ? "rtl" : "ltr";
}

export function getAlternateLocale(locale: Locale): Locale {
  return locale === "ar" ? "en" : "ar";
}

export function getLocaleHref(pathname: string, locale: Locale): string {
  const segments = pathname.split("/").filter(Boolean);

  if (segments.length > 0 && isLocale(segments[0])) {
    segments[0] = locale;
    return \`/\${segments.join("/")}\`;
  }

  return pathname === "/" ? \`/\${locale}\` : \`/\${locale}\${pathname}\`;
}

export function getLocaleFromPathname(pathname: string): Locale {
  const localeSegment = pathname.split("/").filter(Boolean)[0];

  return isLocale(localeSegment) ? localeSegment : defaultLocale;
}
`;
}

export function getRouteLocaleHookTemplate(): string {
  return `import { useLocation } from "@tanstack/react-router";

import { getDirectionForLocale, getLocaleFromPathname } from "@/lib/i18n";

export function useRouteLocale() {
  const location = useLocation();
  const locale = getLocaleFromPathname(location.pathname);
  const direction = getDirectionForLocale(locale);

  return {
    locale,
    direction,
    pathname: location.pathname,
  };
}
`;
}

export function getResourceStoreTemplate(): string {
  return `export const resources = {
  en: {
    translation: {
      StarterShell: {
        eyebrow: "Forge",
        heading: "Your starter is ready to customize.",
        description:
          "Replace this screen in src/routes/$locale/index.tsx. Edit src/components/ for UI pieces, or src/i18n/resources.ts for translated copy.",
      },
      ThemeToggle: {
        fallbackLabel: "Theme",
        toLightLabel: "Light",
        toDarkLabel: "Dark",
      },
      LanguageToggle: {
        label: "Arabic",
      },
      Fallback: {
        eyebrow: "Forge",
        notFoundTitle: "Page not found.",
        notFoundDescription: "This route does not exist yet.",
        errorTitle: "Something went wrong.",
        errorDescription: "An unexpected error occurred. Please try again.",
        homeLabel: "Go home",
        retryLabel: "Try again",
      },
    },
  },
  ar: {
    translation: {
      StarterShell: {
        eyebrow: "فورج",
        heading: "الواجهة جاهزة لتبدأ التعديل.",
        description:
          "استبدل هذه الشاشة من src/routes/$locale/index.tsx. عدل src/components/ لعناصر الواجهة، أو src/i18n/resources.ts للنصوص المترجمة.",
      },
      ThemeToggle: {
        fallbackLabel: "المظهر",
        toLightLabel: "فاتح",
        toDarkLabel: "داكن",
      },
      LanguageToggle: {
        label: "English",
      },
      Fallback: {
        eyebrow: "فورج",
        notFoundTitle: "الصفحة غير موجودة.",
        notFoundDescription: "هذا المسار غير موجود بعد.",
        errorTitle: "حدث خطأ ما.",
        errorDescription: "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",
        homeLabel: "العودة للرئيسية",
        retryLabel: "أعد المحاولة",
      },
    },
  },
} as const;
`;
}

export function getI18nTypesTemplate(): string {
  return `import { resources } from "@/i18n/resources";

export type TranslationResources = typeof resources;
export type TranslationNamespace = keyof TranslationResources["en"];
export type TranslationLocale = keyof TranslationResources;
`;
}

export function getI18nConfigTemplate(): string {
  return `import { createInstance } from "i18next";
import { initReactI18next } from "react-i18next";

import { resources } from "@/i18n/resources";
import { defaultLocale, locales, type Locale } from "@/lib/i18n";

export function createI18nInstance(locale: Locale) {
  const i18n = createInstance();

  void i18n.use(initReactI18next).init({
    resources,
    lng: locale,
    fallbackLng: defaultLocale,
    supportedLngs: [...locales],
    ns: ["translation"],
    defaultNS: "translation",
    interpolation: {
      escapeValue: false,
    },
    react: {
      useSuspense: false,
    },
    initAsync: false,
  });

  return i18n;
}
`;
}

export function getViteConfigTemplate(): string {
  return `import { defineConfig } from "vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import viteReact from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { nitro } from "nitro/vite";

export default defineConfig({
  resolve: {
    tsconfigPaths: true,
  },
  plugins: [nitro(), tailwindcss(), tanstackStart(), viteReact()],
});
`;
}
