import { HeadContent, ScriptOnce, Scripts, createRootRoute } from "@tanstack/react-router"
import appCss from "../styles.css?url"
import type * as React from "react"

import { AppProviders } from "@/components/app-providers"
import { FallbackActions } from "@/components/fallback-actions"
import { FallbackScreen } from "@/components/fallback-screen"
import { RouteError } from "@/components/route-error"

export const Route = createRootRoute({
  head: () => ({
    meta: [
      {
        charSet: "utf-8",
      },
      {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
      },
      {
        title: "forge-start-base-ltr-fixture",
      },
      {
        name: "description",
        content: "Starter app generated by Forge for forge-start-base-ltr-fixture.",
      },
      {
        name: "robots",
        content: "index, follow",
      },
      {
        property: "og:title",
        content: "forge-start-base-ltr-fixture",
      },
      {
        property: "og:description",
        content: "Starter app generated by Forge for forge-start-base-ltr-fixture.",
      },
      {
        property: "og:type",
        content: "website",
      },
      {
        name: "twitter:card",
        content: "summary_large_image",
      },
      {
        name: "twitter:title",
        content: "forge-start-base-ltr-fixture",
      },
      {
        name: "twitter:description",
        content: "Starter app generated by Forge for forge-start-base-ltr-fixture.",
      },
    ],
    links: [
      {
        rel: "icon",
        href: "/favicon.ico",
        sizes: "any",
        type: "image/x-icon",
      },
      {
        rel: "shortcut icon",
        href: "/favicon.ico",
        type: "image/x-icon",
      },
      {
        rel: "manifest",
        href: "/site.webmanifest",
      },
      {
        rel: "stylesheet",
        href: appCss,
      },
    ],
  }),
  errorComponent: RootErrorScreen,
  shellComponent: RootDocument,
  notFoundComponent: RootNotFoundScreen,
})

function RootDocument({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <head>
        <meta name="color-scheme" content="dark light" />
        <HeadContent />
      </head>
      <body className="min-h-svh bg-background font-sans text-foreground antialiased">
        <ScriptOnce>
          {
            '(function(){try{var root=document.documentElement;var stored=localStorage.getItem("theme");var theme=stored==="light"||stored==="dark"||stored==="system"?stored:"system";var resolved=theme==="system"?(window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"):theme;root.classList.remove("light","dark");root.classList.add(resolved);root.style.colorScheme=resolved;}catch(_error){}})();'
          }
        </ScriptOnce>
        <AppProviders>{children}</AppProviders>
        <Scripts />
      </body>
    </html>
  )
}

function RootNotFoundScreen() {
  return (
    <FallbackScreen
      title="Page not found."
      description="This route does not exist yet."
      action={<FallbackActions homeHref="/" homeLabel="Go home" />}
    />
  )
}

function RootErrorScreen({ reset }: { error: unknown; reset: () => void }) {
  return <RouteError onRetry={reset} />
}
