import {
  HeadContent,
  ScriptOnce,
  Scripts,
  createRootRoute,
  useLocation,
  useNavigate,
} from "@tanstack/react-router"
import appCss from "../styles.css?url"
import type * as React from "react"
import { AppProviders } from "@/components/app-providers"
import { Button } from "@/components/ui/button"
import { FallbackScreen } from "@/components/fallback-screen"
import { useUiSound } from "@/hooks/use-ui-sound"
import { RouteError } from "@/components/route-error"

export const Route = createRootRoute({
  head: () => ({
    meta: [
      {
        charSet: "utf-8",
      },
      {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
      },
      {
        title: "regen-start-base-ltr",
      },
      {
        name: "description",
        content: "Starter app generated by Forge for regen-start-base-ltr.",
      },
      {
        name: "robots",
        content: "index, follow",
      },
      {
        property: "og:title",
        content: "regen-start-base-ltr",
      },
      {
        property: "og:description",
        content: "Starter app generated by Forge for regen-start-base-ltr.",
      },
      {
        property: "og:type",
        content: "website",
      },
      {
        name: "twitter:card",
        content: "summary_large_image",
      },
      {
        name: "twitter:title",
        content: "regen-start-base-ltr",
      },
      {
        name: "twitter:description",
        content: "Starter app generated by Forge for regen-start-base-ltr.",
      },
    ],
    links: [
      {
        rel: "icon",
        href: "/favicon.ico",
        sizes: "any",
        type: "image/x-icon",
      },
      {
        rel: "shortcut icon",
        href: "/favicon.ico",
        type: "image/x-icon",
      },
      {
        rel: "manifest",
        href: "/site.webmanifest",
      },
      {
        rel: "stylesheet",
        href: appCss,
      },
    ],
  }),
  errorComponent: RootErrorScreen,
  shellComponent: RootDocument,
  notFoundComponent: NotFoundScreen,
})

function RootDocument({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <head>
        <meta name="color-scheme" content="dark light" />
        <HeadContent />
      </head>
      <body className="min-h-svh bg-background font-sans text-foreground antialiased">
        <ScriptOnce>
          {
            '(function(){try{var root=document.documentElement;var stored=localStorage.getItem("theme");var theme=stored==="light"||stored==="dark"||stored==="system"?stored:"system";var resolved=theme==="system"?(window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"):theme;root.classList.remove("light","dark");root.classList.add(resolved);root.style.colorScheme=resolved;}catch(_error){}})();'
          }
        </ScriptOnce>
        <AppProviders>{children}</AppProviders>
        <Scripts />
      </body>
    </html>
  )
}

function NotFoundScreen() {
  const location = useLocation()
  const navigate = useNavigate()
  const { playSound } = useUiSound()
  const copy =
    location.pathname.split("/").filter(Boolean)[0] === "ar"
      ? {
          title: "الصفحة غير موجودة.",
          description: "هذا المسار غير موجود بعد في الواجهة المولدة.",
          backLabel: "الرجوع",
          homeLabel: "العودة للرئيسية",
        }
      : {
          title: "Page not found.",
          description: "This route does not exist in the generated starter yet.",
          backLabel: "Go back",
          homeLabel: "Go home",
        }
  const segments = location.pathname.split("/").filter(Boolean)
  const homeHref =
    segments.length > 0 && (segments[0] === "en" || segments[0] === "ar") ? `/${segments[0]}` : "/"

  return (
    <FallbackScreen
      title={copy.title}
      description={copy.description}
      action={
        <>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="h-9 rounded-full px-3"
            onClick={() => {
              playSound("click-soft")
              window.history.back()
            }}
          >
            {copy.backLabel}
          </Button>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="h-9 rounded-full px-3"
            onClick={() => {
              playSound("click-soft")
              navigate({ to: homeHref })
            }}
          >
            {copy.homeLabel}
          </Button>
        </>
      }
    />
  )
}

function RootErrorScreen({ reset }: { error: unknown; reset: () => void }) {
  return <RouteError onRetry={reset} />
}
